// AUTO-GENERATED BY scripts/build-index.ts — DO NOT EDIT MANUALLY
// Run `npm run registry:index` to regenerate.
import { lazy } from 'react'

export type RegistryEntry = {
  files: string[]
  component: ReturnType<typeof lazy>
}

const Demo0 = lazy(() => import('@/registry/examples/copy-button-demo'))
const Demo1 = lazy(() => import('@/registry/examples/package-manager-tabs-demo'))

export const Index: Record<string, RegistryEntry> = {
  'copy-button': {
    files: ['registry/ui/copy-button.tsx'],
    component: Demo0,
  },
  'package-manger-tabs': {
    files: [],
    component: Demo1,
  },
}
