#!/usr/bin/env tsx

/**
 * Registry Index Generator
 *
 * Scans registry/examples/ for *-demo.tsx files and emits
 * components/registry/index.tsx — a lazy-component map keyed by slug.
 *
 * Run:  npm run registry:index
 * Auto: predev / prebuild hooks
 */
import fs from 'fs'
import path from 'path'

const ROOT = process.cwd()
const UI_DIR = path.join(ROOT, 'registry/ui')
const EXAMPLES_DIR = path.join(ROOT, 'registry/examples')
const OUT_FILE = path.join(ROOT, 'components/registry/index.tsx')

function readTsxFiles(dir: string): string[] {
  if (!fs.existsSync(dir)) return []
  return fs.readdirSync(dir).filter((f) => f.endsWith('.tsx'))
}

/** "copy-button-demo.tsx" → "copy-button" */
function toSlug(filename: string): string {
  return path.basename(filename, '.tsx').replace(/-demo$/, '')
}

function main(): void {
  const demoFiles = readTsxFiles(EXAMPLES_DIR).filter((f) => f.endsWith('-demo.tsx'))

  // Map slug → ui source file path
  const uiMap = new Map<string, string>()
  for (const file of readTsxFiles(UI_DIR)) {
    uiMap.set(path.basename(file, '.tsx'), `registry/ui/${file}`)
  }

  const lazyDecls: string[] = []
  const indexEntries: string[] = []

  demoFiles.forEach((file, i) => {
    const slug = toSlug(file)
    const demoModule = `registry/examples/${path.basename(file, '.tsx')}`
    const uiFile = uiMap.get(slug)

    lazyDecls.push(`const Demo${i} = lazy(() => import('@/${demoModule}'))`)
    indexEntries.push(
      `  '${slug}': {\n` +
        `    files: [${uiFile ? `'${uiFile}'` : ''}],\n` +
        `    component: Demo${i},\n` +
        `  },`
    )
  })

  const output = `\
// AUTO-GENERATED BY scripts/build-index.ts — DO NOT EDIT MANUALLY
// Run \`npm run registry:index\` to regenerate.
/* eslint-disable */
import { lazy } from 'react'

export type RegistryEntry = {
  files: string[]
  component: ReturnType<typeof lazy>
}

${lazyDecls.join('\n')}

export const Index: Record<string, RegistryEntry> = {
${indexEntries.join('\n')}
}
`

  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true })
  fs.writeFileSync(OUT_FILE, output, 'utf-8')

  console.log(`Registry index → components/registry/index.tsx`)
  if (demoFiles.length === 0) {
    console.log('    No demo files found in registry/examples/')
  } else {
    demoFiles.forEach((f) => console.log(`    · ${toSlug(f)}`))
  }
}

main()
